version: "3.9"

services:
  backend:
    build: ./backend
    container_name: siem-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/logs:/app/logs
    environment:
      - DB_PATH=/app/logs/siem.db
      - ALERT_WEBHOOK=https://hooks.slack.com/services/XXXX/XXXX/XXXX
    depends_on:
      - elasticsearch

  frontend:
    build: ./frontend
    container_name: siem-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

volumes:
  esdata:
